# Generated by Django 3.0.3 on 2020-05-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20200514_1708'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='facturaPayment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contract.Invoice'),
        ),
    ]
