# Generated by Django 3.0.3 on 2020-05-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20200514_1708'),
        ('commercial', '0003_remove_commercialinvoice_invoiceservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialinvoice',
            name='Invoice',
            field=models.ManyToManyField(related_name='Invoice', to='contract.Invoice'),
        ),
    ]
