# Generated by Django 3.0.3 on 2020-05-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0004_commercialinvoice_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommercialInvoice',
        ),
    ]
