# Generated by Django 3.0.3 on 2020-05-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contrat_number',
        ),
    ]
