# Generated by Django 3.0.3 on 2020-05-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_client_contrat_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='billing',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='client',
            name='financial_state',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stratus',
        ),
    ]
