# Generated by Django 3.0.3 on 2020-05-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energytransfers', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historys', to='energytransfers.Counter'),
        ),
    ]
