# Generated by Django 3.0.3 on 2020-05-14 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contractNumber', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('codeInvoice', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumptiondaysInvoice', models.PositiveIntegerField()),
                ('paymentdeadlineInvoice', models.DateField()),
                ('billingdateInvoice', models.DateField(default=datetime.date.today)),
                ('stateInvoice', models.BooleanField(default=False)),
                ('referencecodeInvoice', models.CharField(max_length=30)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='invoiceservices',
            name='client',
        ),
    ]
