# Generated by Django 3.0.3 on 2020-05-14 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20200514_1708'),
        ('users', '0002_remove_client_contrat_number'),
        ('payments', '0002_auto_20200514_1708'),
        ('energytransfers', '0002_auto_20200514_1708'),
        ('commercial', '0004_commercialinvoice_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvoiceServices',
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='users.Client'),
        ),
        migrations.AddField(
            model_name='contract',
            name='counter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counter', to='energytransfers.Counter'),
        ),
    ]
