# Generated by Django 3.0.3 on 2020-05-14 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20200514_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='contract.Contract'),
            preserve_default=False,
        ),
    ]
