# Generated by Django 3.0.3 on 2020-05-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_invoice_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='contract.Contract'),
        ),
    ]
