# Generated by Django 3.0.3 on 2020-05-18 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20200518_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='consumptiondaysInvoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='basicTake',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='currentRecord',
            field=models.PositiveIntegerField(default=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='intakes',
            field=models.CharField(default='05-13,04-41', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='pastRecord',
            field=models.PositiveIntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='payMonth',
            field=models.DateField(default='2020-05-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='remainder',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='stratum',
            field=models.PositiveSmallIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='unitaryValue',
            field=models.PositiveIntegerField(default=589),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='codeInvoice',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='invoicenumber'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentdeadlineInvoice',
            field=models.DateField(default=datetime.datetime(2020, 5, 28, 20, 35, 42, 976443)),
        ),
    ]
