# Generated by Django 3.0.3 on 2020-05-19 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_auto_20200518_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paymentdeadlineInvoice',
            field=models.DateField(default=datetime.datetime(2020, 5, 29, 1, 55, 52, 679914)),
        ),
    ]
