# Generated by Django 3.0.3 on 2020-05-19 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_auto_20200519_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.CharField(default='Cra. 1B #5450', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='counter',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paymentdeadlineInvoice',
            field=models.DateField(default=datetime.datetime(2020, 5, 29, 15, 32, 50, 486361)),
        ),
    ]
