# Generated by Django 3.0.3 on 2020-05-19 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_auto_20200519_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='billingdateInvoice',
            new_name='billingDate',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payMonth',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paymentdeadlineInvoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='deadDatePay',
            field=models.DateField(default=datetime.datetime(2020, 5, 29, 15, 47, 19, 229862)),
        ),
    ]
