# Generated by Django 3.0.3 on 2020-05-19 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_auto_20200519_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mora',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='deadDatePay',
            field=models.DateField(default=datetime.datetime(2020, 5, 29, 20, 49, 43, 887048)),
        ),
    ]
