# Generated by Django 3.0.3 on 2020-05-20 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_auto_20200519_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='deadDatePay',
            field=models.DateField(default=datetime.datetime(2020, 5, 30, 12, 50, 30, 561744)),
        ),
    ]
