# Generated by Django 3.0.3 on 2020-05-21 12:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energytransfers', '0006_remove_counter_clientcounter'),
        ('contract', '0020_auto_20200521_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='interes_mora',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='counter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='counter', to='energytransfers.Counter'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='deadDatePay',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 12, 34, 54, 455752)),
        ),
    ]
