# Generated by Django 3.0.3 on 2020-05-21 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0026_auto_20200521_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='deadDatePay',
            field=models.DateField(default=datetime.datetime(2020, 5, 31, 22, 51, 43, 474278)),
        ),
    ]
