# Generated by Django 3.0.3 on 2020-05-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('codeCounter', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitudeCounter', models.CharField(max_length=255)),
                ('lengthCounter', models.CharField(max_length=255)),
                ('counter', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('addressCounter', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Substation',
            fields=[
                ('codeSubstation', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitudeSubstation', models.CharField(max_length=255)),
                ('lengthSubstation', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transformator',
            fields=[
                ('codeTransformator', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitudeTransformator', models.CharField(max_length=255)),
                ('lengthTransformator', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('substationTransformator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energytransfers.Substation')),
            ],
        ),
    ]
