# Generated by Django 3.0.3 on 2020-05-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energytransfers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='counter',
            new_name='value',
        ),
    ]
