# Generated by Django 3.0.3 on 2020-05-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energytransfers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='clientCounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='users.Client'),
        ),
        migrations.AddField(
            model_name='counter',
            name='transformatorCounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energytransfers.Transformator'),
        ),
    ]
