# Generated by Django 3.0.3 on 2020-05-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energytransfers', '0003_counter_stratum'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='current',
            field=models.PositiveIntegerField(default=400),
            preserve_default=False,
        ),
    ]
