# Generated by Django 3.0.3 on 2020-05-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energytransfers', '0004_history_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='value',
            field=models.PositiveIntegerField(),
        ),
    ]
