# Generated by Django 3.0.3 on 2020-05-19 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energytransfers', '0005_auto_20200518_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='clientCounter',
        ),
    ]
