# Generated by Django 3.0.3 on 2020-05-11 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_days', models.PositiveIntegerField()),
                ('payment_deadline', models.DateField()),
                ('billing_date', models.DateField(default=datetime.date.today)),
                ('state', models.BooleanField(default=False)),
                ('reference_code', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateField()),
                ('final_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(default=datetime.time)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='factures.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='Publicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=15)),
                ('url_resource', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('transaction_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='factures.Payment')),
            ],
        ),
        migrations.CreateModel(
            name='DirectPayment',
            fields=[
                ('transaction_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='factures.Payment')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='history',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='factures.History'),
        ),
        migrations.AddField(
            model_name='bill',
            name='publicity',
            field=models.ManyToManyField(to='factures.Publicity'),
        ),
    ]
