# Generated by Django 3.0.3 on 2020-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='consumption',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
    ]
