# Generated by Django 3.0.3 on 2020-05-14 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('factures', '0002_history_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceservices',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='users.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceservices',
            name='total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
